version: '3'
services:
  db:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: myproject123
      POSTGRES_DB: hospital-datastore
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U test -d hospital-datastore" ]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  server:
    build: .
    container_name: server
    environment:
      - IS_LOCAL_DEPLOYMENT=true
      - AUTH_DB_HOST=db
      - AUTH_DB_NAME=hospital-datastore
      - AUTH_DB_USER=test
      - AUTH_DB_PASSWORD=myproject123
      - AUTH_DB_PORT=5432
    ports:
      - "9090:8080"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/homeopathic-doctor-assistant
    networks:
      - default
volumes:
  db-data:
