version: '3'
services:
  db:
    image: postgres:13
    container_name: db
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: myproject123
      POSTGRES_DB: hospital-datastore
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U test -d hospital-datastore" ]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - default

  server:
    build:
      context: ./homeopathic-doctor-assistant
      dockerfile: Dockerfile
    container_name: server
    environment:
      - IS_LOCAL_DEPLOYMENT=true
      - AUTH_DB_HOST=db
      - AUTH_DB_NAME=hospital-datastore
      - AUTH_DB_USER=test
      - AUTH_DB_PASSWORD=myproject123
      - AUTH_DB_PORT=5432
    ports:
      - "9090:8080"
    depends_on:
      db:
        condition: service_healthy

    networks:
      - default
  app:
    build:
      context: ./mab-web
      dockerfile: Dockerfile
    container_name: app
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:9090/v1
    #restart: unless-stopped
    networks:
      - default

volumes:
  db-data:
